### ISSUE TITLE
Can you provide the code for generating pkl-file?

### ISSUE THREAD

**Issue by Maojianzeng** [V-Sense/ACTION-Net#15]
Thank you very much for providing the source code of this project, I want to use this project to experiment on the Something-Something V1, but the annotation file of the Something-Something V1 is in csv format, I am having difficulty with how to generate the pkl-file. Can you provide the code to generate the pkl-file or the pkl-file about the Something-Something V1. Thanks.

**Comment by lwyupupup** [comment]
> Thank you very much for providing the source code of this project, I want to use this project to experiment on the Something-Something V1, but the annotation file of the Something-Something V1 is in csv format, I am having difficulty with how to generate the pkl-file. Can you provide the code to generate the pkl-file or the pkl-file about the Something-Something V1. Thanks.
Have you solved the problem？Can you contact me if you 've already solved it? My QQ email is 3177288121@qq.com
