### ISSUE TITLE
Question of the paper

### ISSUE THREAD

**Issue by kinfeparty** [V-Sense/ACTION-Net#2]
Hello! I want to ask a question about the paper.

![捕获](https://user-images.githubusercontent.com/35788879/114200225-925af000-9987-11eb-8242-3f63a3cf7125.PNG)

Do you directly use the result of C3D:Resnext101 in their paper or train the model by yourself?

Thanks!

**Comment by villawang** [comment]
> Hello! I want to ask a question about the paper.
> 
> ![捕获](https://user-images.githubusercontent.com/35788879/114200225-925af000-9987-11eb-8242-3f63a3cf7125.PNG)
> 
> Do you directly use the result of C3D:Resnext101 in their paper or train the model by yourself?
> 
> Thanks!

Hi there,

For the EgoGesture, we just directly use the result from the reference [17]. For the jester, we use the pre-trained Kinetics models and retrain on the Jester, which is provided at [here](https://github.com/villawang/3D-ResNets-PyTorch).

**Comment by kinfeparty** [comment]
> > Hello! I want to ask a question about the paper.
> > ![捕获](https://user-images.githubusercontent.com/35788879/114200225-925af000-9987-11eb-8242-3f63a3cf7125.PNG)
> > Do you directly use the result of C3D:Resnext101 in their paper or train the model by yourself?
> > Thanks!
> 
> Hi there,
> 
> For the EgoGesture, we just directly use the result from the reference [17]. For the jester, we use the pre-trained Kinetics models and retrain on the Jester, which is provided at [here](https://github.com/villawang/3D-ResNets-PyTorch).

Thanks for you answer!
