### ISSUE TITLE
The result of CAM

### ISSUE THREAD

**Issue by ZhouCX117** [V-Sense/ACTION-Net#3]
Hi! Thank you for your wonderful project! Could you release the code for the CAM picture? I want to learn more about visualization.

**Comment by villawang** [comment]
> Hi! Thank you for your wonderful project! Could you release the code for the CAM picture? I want to learn more about visualization.

Hi there,

We just do not want to keep repo too complicated. There are lots of resources on the internet about CAM or grad-CAM and you are able to get instructions there then use them with our models.

**Comment by catherinezll95** [comment]
Thanks~
