### ISSUE TITLE
Problems with PKL file generation

### ISSUE THREAD

**Issue by kkk241-q** [V-Sense/ACTION-Net#7]
Hi, I'm a newbie. I would like to ask what is the code on the Jester dataset, something-something V2 dataset and generating the training, testing, and validating PKL files?

**Comment by villawang** [comment]
> Hi, I'm a newbie. I would like to ask what is the code on the Jester dataset, something-something V2 dataset and generating the training, testing, and validating PKL files?

Hi there, you can follow our generalized PKL files to generate annotations for yours.

**Comment by kkk241-q** [comment]
> > Hi, I'm a newbie. I would like to ask what is the code on the Jester dataset, something-something V2 dataset and generating the training, testing, and validating PKL files?
> 
> Hi there, you can follow our generalized PKL files to generate annotations for yours.

Can you give me a jester data set into pkl data code, that is very helpful to me

**Comment by villawang** [comment]
> > > Hi, I'm a newbie. I would like to ask what is the code on the Jester dataset, something-something V2 dataset and generating the training, testing, and validating PKL files?
> > 
> > 
> > Hi there, you can follow our generalized PKL files to generate annotations for yours.
> 
> Can you give me a jester data set into pkl data code, that is very helpful to me

You can have a try to load our provided pkl file and then modify each row to yours. This is the best way to do this. Convert code is messy.

**Comment by ZooHam** [comment]
Hi, I find the lables of jester's test.pkl are all 0. And when I run the test_jester_8f.sh, I get top1 =3.4 and top5 =16.7 witch mode is 'val' and use val.pkl. And get top1 =0, top5 = 100 witch mode is 'test' and use test.pkl.
