### ISSUE TITLE
About online inference mode

### ISSUE THREAD

**Issue by gd2016229035** [V-Sense/ACTION-Net#8]
Can Action-Net run as an online inference version(frame by frame input) like TSM(https://github.com/mit-han-lab/temporal-shift-module/tree/master/online_demo)?

**Comment by villawang** [comment]
> Can Action-Net run as an online inference version(frame by frame input) like TSM(https://github.com/mit-han-lab/temporal-shift-module/tree/master/online_demo)?

Hi, thanks for your interesting question! As the motion module in the Action requires two adjacent frames, so it might have problems in ingesting frame by frame input. We will investigate this online scenario in the future.

**Comment by gd2016229035** [comment]
Online inference is important for edge devices. Please let me know if you release an online version! : )

**Comment by villawang** [comment]
> Online inference is important for edge devices. Please let me know if you release an online version! : )

Will do !

**Comment by villawang** [comment]
> Online inference is important for edge devices. Please let me know if you release an online version! : )

Will do !
